# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# This is an example of using VeraDemo Java test application with the Veracode Static Pipeline scanner.  A Veracode subscription is required.
trigger:
- main
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build app and unit tests
  jobs: 
  - job: Build
    # condition: "false"
    steps:
    - task: Maven@3
      displayName: Build with Maven
      inputs:
        mavenPomFile: 'app/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    # - publish: /home/vsts/work/1/s/app/target/verademo.war
    - publish: $(System.DefaultWorkingDirectory)/app/target/verademo.war
      displayName: 'Publish app for testing'
      artifact: verademo.war

- stage: Test
  displayName: AppSec testing
  dependsOn: Build
  jobs: 
  - job: SCA
    # condition: "false"
    steps:
    - task: Bash@3
      displayName: 'Veracode SCA'
      inputs:
        targetType: 'inline'
        script: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan ./app --update-advisor
          # curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan ./app --json ./scaResults.json --update-advisor
      # env:
      #   SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)
    # - publish: scaResults.json
    #   artifact: Results

  - job: SAST
    # condition: "false"
    steps: 
    - download: $(System.DefaultWorkingDirectory)
      artifact: verademo.war
    - task: Bash@3
      displayName: Veracode SAST Pipeline Scan
      inputs:
        targetType: 'inline'
        script: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          ls -lh ../
          java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f ./verademo.war || true
    - publish: $(System.DefaultWorkingDirectory)/results.json
      artifact: VeracodeSASTpipeline

- stage: Container
  condition: "false"
  displayName: Containerize and test
  jobs:
  - job: Build_image
    steps:
    - task: Bash@3
      displayName: Build a container image
      inputs:
        targetType: 'inline'
        script: |
          docker pull mariadb:10.6.2
          docker build --no-cache -t verademo .

  - job: Test_image
    steps:
      - task: Bash@3
        displayName: 'Container image scan'
        inputs:
          targetType: 'inline'
          script: |
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
            export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
            ./veracode scan --type image --source veracode scan --type image \
              --source juliantotzek/verademo:latest --output verademo.json

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'verademo.json'
          ArtifactName: 'VeracodeContainerScan'
          publishLocation: 'Container'

# - task: Bash@3
#   displayName: 'Policy check'
#   inputs:
#     targetType: 'inline'
#     script: |
#       PASS=$(jq -r '."policy-passed"' verademo.json)
#       echo "Passed policy: $PASS"
#       if $PASS; then
#         exit 0
#       else
#         exit 1
#       fi
